model:
    name: 'SelfSupModel'
    depth_net:
        name: 'WavPackNet'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (384, 1280)
    test:
        dataset: ['KITTI']
        path: ['/media/lqin/easystore/Dataset/KITTI/Depth/raw_data/']
        split: ['splits/eigen_split/eigen_test_files.txt']
        depth_type: ['groundtruth']
save:
    folder: 'results/save'
    depth:
        rgb: True
        viz: True
        npz: True
        png: True
